# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_size',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
