# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-15 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_author_app', '0002_auto_20191015_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
