# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-15 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_author_app', '0003_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='book_author_app.Book'),
        ),
    ]
