# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-14 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='ninjas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dojo_ninjas_app.Dojo'),
            preserve_default=False,
        ),
    ]
